spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 2s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    password: 123456
    lettuce:
          pool:
            # 最大空闲连接数 默认8
            max-idle: 8
            # 最小空闲连接数 默认0
            min-idle: 0
             # 最大活跃链接数 默认8
            max-active: 8
          shutdown-timeout: 100ms
