
spring:
  application:
    name: mybaties-plus
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_transaction_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: liuhao
    password: liuhao
  redis:
    host: 127.0.0.1
logging:
  level.liuhao.memo: debug
##idtype 设置主键生成方式
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
